apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
